# -*- coding: utf-8 -*-
"""final18

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nYXygbJr8ynV3uQq8gwtA1oX5Tqa9jPn
"""

#นาย ปริญญา สุวรรณมาลี เลขที่18 ม.4/4

import random

def guessing_game():
    print("ยินดีต้อนรับสู่เกมทายตัวเลข!")
    print("ฉันกำลังคิดเลขระหว่าง 1 ถึง 10 คุณทายได้ไหม?")

    secret_number = random.randint(1, 10)
    attempts = 0
    guess = 0

    while guess != secret_number:
        try:
            guess = int(input("ทายตัวเลขของคุณ (1-10): "))
            attempts += 1

            if guess < 1 or guess > 10:
                print("กรุณาใส่ตัวเลขระหว่าง 1 ถึง 10 เท่านั้น.")
            elif guess < secret_number:
                print("น้อยเกินไป! ลองใหม่อีกครั้ง.")
            elif guess > secret_number:
                print("มากเกินไป! ลองใหม่อีกครั้ง.")
        except ValueError:
            print("คุณต้องใส่ตัวเลขเท่านั้น. กรุณาลองใหม่.")

    print(f"ถูกต้อง! คุณทายถูกในครั้งที่ {attempts} ตัวเลขที่ถูกต้องคือ {secret_number}.")
    print("จบเกมแล้ว. ขอบคุณที่เล่น!")

guessing_game()