# -*- coding: utf-8 -*-
"""final18

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nYXygbJr8ynV3uQq8gwtA1oX5Tqa9jPn
"""

import random

secret_number = random.randint(1, 10)
guess = 0
attempts = 0

print("มาเล่นเกมทายตัวเลขกันเถอะ! ฉันคิดเลข 1-10 ไว้นะ")

while guess != secret_number:
    try:
        guess = int(input("ทายตัวเลข: "))
        attempts += 1

        if guess < secret_number:
            print("น้อยไป!")
        elif guess > secret_number:
            print("มากไป!")
    except ValueError:
        print("กรุณาใส่แค่ตัวเลขนะ")

print(f"เก่งมาก! ถูกต้องแล้ว! คือ {secret_number} คุณทายไป {attempts} ครั้ง")